[package]
name = "rust-sqlx-mysql-one"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"
serde = { version = "1.0.150", features = ["derive"] }
sqlx = { version = "0.8.0", features = ["runtime-actix-rustls", "mysql", "macros"] }
futures = "0.3.25"
